url_prefix: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/test-camrange"
#malapert massif
#MINLON: -5.673513
#MAXLON: 5.073011
#MINLAT: -86.20588
#MAXLAT: -85.497357
#connecting ridge
MINLON: -172.318538
MAXLON: -102.226492
MINLAT: -89.835617
MAXLAT: -89.068587
img_prefix: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Thomas_practice/NAC_DTM_ESALL_CR1/imgs"
#img_prefix: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/imgs_sample"
#img_prefix: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Malapert_Massif"
#img_prefix: "/home/ec2-user/SageMaker/Viktoriia_practice/118img_sample/imgs_sample"
ames_prefix: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/ames_stereo_pipeline/StereoPipeline-3.5.0-alpha-2024-07-24-x86_64-Linux/bin"
#initial_dem: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/DTM-initial/Connecting-Ridge_Site01_final_adj_5mpp_surf.tif"
directory_path: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/test-camrange/experiment"
cam_path: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/imgs_sample"
shape_path: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/shape"
map: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/map/connecting_ridge.map"
#map: "/home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/map/Malapert.map"
unique_basenames: /home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/unique_basenames.lis
directory_path_pyt: /home/ec2-user/SageMaker/Artemis_III_Sites_Alex_Coordinates/Connecting_Ridge/Viktoriia_practice/test-camrange/experiment
custom_footprint: false
